### ISSUE TITLE
timeout in get request

### ISSUE THREAD

**Issue by kris927b** [jemaf/stackoverflow-jobs#1]
Hello @jemaf 

Thank you for making such a good library! 

I have come across that the get request in the `Query.execute()` often hangs indefinitely. 
I would like to suggest that you add a timeout parameter as stated [here](https://requests.readthedocs.io/en/master/user/quickstart/#timeouts).

**Comment by jemaf** [comment]
Hi @kris927b 

Good catch!
I'm gonna work on this improvement in the next days.

Thanks for the suggestion!

**Comment by jemaf** [comment]
Hi @kris927b, 

I've just updated a new version (0.1.0) in [PyPI](https://pypi.org/project/stackoverflow-jobs/) with the support to requests timeout.
You can check the instructions on how to use it in the new [README](https://github.com/jemaf/stackoverflow-jobs#stackoverflow-jobs) file.

Please let me know if you have any questions.

I'm going to close this issue for now, but feel free to open other ones! :-)
